# Generated by Django 4.0.4 on 2024-12-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=10)),
                ('appointment_date', models.DateField()),
            ],
        ),
    ]
