# Generated by Django 4.0.4 on 2024-12-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nethra_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='age',
        ),
    ]
