# Generated by Django 4.0.4 on 2024-12-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethra_app', '0002_remove_appointment_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='dob',
        ),
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.CharField(default='20', max_length=10),
        ),
    ]
