# Generated by Django 4.0.4 on 2024-12-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethra_app', '0003_remove_appointment_dob_appointment_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='age',
            field=models.CharField(max_length=10),
        ),
    ]
